---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ic-app
        deployment: ic-app
    spec:
      containers:
        - name: insurance-claim-processing-git
          image: quay.io/rh-aiservices-bu/rhoai-lab-insurance-claim-app:1.1
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: INFERENCE_SERVER_URL
              value: http://llm.ic-shared-llm.svc.cluster.local:3000/
            - name: MAX_NEW_TOKENS
              value: '1024'
            - name: TOP_K
              value: '10'
            - name: TOP_P
              value: '0.95'
            - name: TYPICAL_P
              value: '0.95'
            - name: TEMPERATURE
              value: '0.01'
            - name: REPETITION_PENALTY
              value: '1.03'
            - name: POSTGRES_HOST
              value: claimdb.ic-shared-db.svc.cluster.local
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: claimdb
                  key: database-name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: claimdb
                  key: database-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: claimdb
                  key: database-password
            - name: POSTGRES_PORT
              value: '5432'
            - name: S3_ENDPOINT_URL
              value: http://minio.ic-shared-minio.svc.cluster.local:9000
            - name: IMAGES_BUCKET
              value: claim-images
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: miniocreds
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: miniocreds
                  key: aws_secret_access_key
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600