---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: ic-claim-app

resources:
# wave 0
- secret-db.yaml
- secret-minio.yaml
- pvc-db.yaml
- sql-script-configmap.yaml
# wave 1
- deployment-db.yaml
- service-db.yaml
- db-init-job.yaml
- populate-images.yaml
# wave 2
- deployment-app.yaml
- service-app.yaml
- route-app.yaml
